version: '3.5'

networks:
  BallanceRecord:
    name: BallanceRecord
    
services:
  main-api:
    build: BallanceRecordApi/
    restart: always
    ports:
    - "7000:80"
    - "7001:443"
    depends_on:
      - db-server
      - redis
    networks:
      - BallanceRecord
      
  db-server:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "temp233"
    ports:
      - "3306:3306"
    networks:
      - BallanceRecord
    volumes:
      - db_data:/var/lib/mysql
  
  redis:
    image: redis
    container_name: redis
    ports:
    - "6379:6379"

volumes:
  db_data: {}