version: '3.5'

networks:
  BallanceRecord:
    name: BallanceRecord
    
services:
  main-api:
    build: BallanceRecordApi/
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:7000
    ports:
    - "6000:6000"
    depends_on:
      - db-server
      - cache
    networks:
      - BallanceRecord
      
  db-server:
    image: mysql
    container_name: db-server
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "temp233"
      MYSQL_DATABASE: "BallanceRecord"
    ports:
      - "3306:3306"
    networks:
      BallanceRecord:
        aliases:
          - db
    volumes:
      - db_data:/var/lib/mysql
  
  cache:
    image: redis
    container_name: cache
    networks:
      - BallanceRecord
    ports:
      - "6379:6379"

volumes:
  db_data: {}